/oak_d_pro_w1:
  ros__parameters:
    camera:
      i_mx_id: 14442C105161D9D600
      i_nn_type: none
      i_pipeline_type: RGB
/oak_d_pro_w2:
  ros__parameters:
    camera:
      i_mx_id: 14442C10A1FBDAD600
      i_nn_type: none
      i_pipeline_type: RGBD
